"""Generated by Claude (Opus 5.5) 2026-10-02.

Checks that every URL a project's notes mention has been captured in a structured file.
This exists because nightly sweeps kept writing leads only into narrative notes, and the
corpus never saw them: 149 Data Center leads had piled up by 2026-10-02.

Usage:
    python tools/check_leads_captured.py DATA_CENTER_PAPER [--since 2026-10-01]

A URL counts as captured if it appears anywhere in a CSV under <PROJECT>/04_DATA/
(candidate_leads.csv, corpus_inventory.csv, watchlist.csv, the verification files, ...)
or in <PROJECT>/04_DATA/url_ignore.txt. The ignore file is for URLs that are not corpus
leads: literature, tooling, background. Put one URL per line there, with an optional
" # reason" after it.

Exit code 1 if any note from the --since date onward has uncaptured URLs. A nightly run is
not finished until this exits 0 for that night's notes.
"""
import argparse
import csv
import pathlib
import re
import sys

URL_RE = re.compile(r"https?://[^\s)\]>\"'`|]+")


def norm(url: str) -> str:
    url = url.rstrip(".,;:*_")
    url = url.split("#")[0]
    url = re.sub(r"[?&](utm_[^=]+|outputType)=[^&]*", "", url)
    url = re.sub(r"^https?://(www\.)?", "", url)
    return url.rstrip("/").lower()


def captured_urls(data_dir: pathlib.Path) -> set:
    found = set()
    for path in data_dir.rglob("*.csv"):
        text = path.read_text(encoding="utf-8", errors="replace")
        found.update(norm(u) for u in URL_RE.findall(text))
    ignore = data_dir / "url_ignore.txt"
    if ignore.exists():
        for line in ignore.read_text(encoding="utf-8").splitlines():
            line = line.split(" #")[0].strip()
            if line and not line.startswith("#"):
                found.add(norm(line))
    return found


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("project")
    ap.add_argument("--since", default="0000-00-00",
                    help="only check notes whose filename date is >= this (YYYY-MM-DD)")
    args = ap.parse_args()

    root = pathlib.Path(args.project)
    data_dir = root / "04_DATA"
    if not data_dir.exists():
        print(f"FAIL: {data_dir} does not exist. Create it with candidate_leads.csv first.")
        return 1
    have = captured_urls(data_dir)

    missing_total = 0
    for note in sorted((root / "notes").glob("*.md")):
        m = re.match(r"(\d{4}-\d{2}-\d{2})", note.name)
        if not m or m.group(1) < args.since:
            continue
        urls = {norm(u): u for u in URL_RE.findall(note.read_text(encoding="utf-8", errors="replace"))}
        missing = [raw for key, raw in urls.items() if key not in have]
        if missing:
            missing_total += len(missing)
            print(f"\n{note.name}: {len(missing)} uncaptured URL(s)")
            for u in missing:
                print(f"  {u}")
    print(f"\nUNCAPTURED: {missing_total}")
    return 1 if missing_total else 0


if __name__ == "__main__":
    sys.exit(main())
